services:
  api:
    build: ./
    container_name: express_api
    volumes:
      - .:/app
    ports:
      - target: 80
        published : 80 
    env_file:
      - .env
    depends_on:
    - mongo
  mongo:
    image: mongo:6  
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"  
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}  
    volumes:
      - mongo-data:/data/db  

volumes:
  mongo-data:  
  